//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class delivery
    {
        public int deliveryID { get; set; }
        public int userID { get; set; }
        public int ordersID { get; set; }
        public System.DateTime deliveryDate { get; set; }
        public string deliveryStatus { get; set; }
        public string deliveryAddress { get; set; }
        public string deliveryDescription { get; set; }
    
        public virtual order order { get; set; }
        public virtual user user { get; set; }
    }
}
