//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public order()
        {
            this.deliveries = new HashSet<delivery>();
            this.ordersDetails = new HashSet<ordersDetail>();
        }
    
        public int ordersID { get; set; }
        public int userID { get; set; }
        public System.DateTime ordersDate { get; set; }
        public string ordersDescription { get; set; }
    
        public virtual ICollection<delivery> deliveries { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<ordersDetail> ordersDetails { get; set; }
    }
}
