//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordersDetail
    {
        public ordersDetail()
        {
            this.payments = new HashSet<payment>();
        }
    
        public int ordersDetailID { get; set; }
        public int ordersID { get; set; }
        public int productID { get; set; }
        public int quantity { get; set; }
        public string ordersDetailDescription { get; set; }
    
        public virtual order order { get; set; }
        public virtual product product { get; set; }
        public virtual ICollection<payment> payments { get; set; }
    }
}
