//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.ordersDetails = new HashSet<ordersDetail>();
            this.shoppingCarts = new HashSet<shoppingCart>();
        }
    
        public int productID { get; set; }
        public int categoryID { get; set; }
        public string productCode { get; set; }
        public string productName { get; set; }
        public int productQty { get; set; }
        public double productPrice { get; set; }
        public double productDiscount { get; set; }
        public double productDiscountedPrice { get; set; }
        public string productImage { get; set; }
        public string productDescription { get; set; }
    
        public virtual category category { get; set; }
        public virtual ICollection<ordersDetail> ordersDetails { get; set; }
        public virtual ICollection<shoppingCart> shoppingCarts { get; set; }
    }
}
