//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class shoppingCart
    {
        public int shoppingCartID { get; set; }
        public int userID { get; set; }
        public int productID { get; set; }
        public int quantity { get; set; }
        public System.DateTime shoppingCartExpiredDate { get; set; }
    
        public virtual product product { get; set; }
        public virtual user user { get; set; }
    }
}
