//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.deliveries = new HashSet<delivery>();
            this.orders = new HashSet<order>();
            this.payments = new HashSet<payment>();
            this.shoppingCarts = new HashSet<shoppingCart>();
        }
    
        public int userID { get; set; }
        public int roleID { get; set; }
        public string userName { get; set; }
        public string userPassword { get; set; }
        public string userEmail { get; set; }
        public int userPhone { get; set; }
        public string userAddress { get; set; }
        public string userDescription { get; set; }
    
        public virtual ICollection<delivery> deliveries { get; set; }
        public virtual ICollection<order> orders { get; set; }
        public virtual ICollection<payment> payments { get; set; }
        public virtual role role { get; set; }
        public virtual ICollection<shoppingCart> shoppingCarts { get; set; }
    }
}
